name: 'Main-Workflow'

on:
  # push:
  #   branches: [ "qa", "stage", "prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: nodecon.azurecr.io
        username: ${{ secrets.ADMIN_USER }}
        password: ${{ secrets.ADMIN_PASS }}
    - run: |
          docker build -t nodecon/react-test -f Dockerfile.dev .
          docker run -e CI=true nodecon/react-test npm test   

      - name: Generate deployment package
        run: zip -r next.zip . -x '*.git*'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.3.1
        with:
          name: node-app
          path: next.zip


  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.4
        with:
          name: node-app

      - name: "Deploy to Azure WebApp"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: next.zip

      - name: Delete zip file
        run: rm next.zip
   
